name: C/C++ CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependents
      run: |
        sudo apt update
        sudo apt install autopoint
    - name: autogen.sh
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make  -j
    - name: make check
      run: make check  -j
    - name: make distcheck
      run: make distcheck  -j
